apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: guestcluster-operator
  name: guestcluster-operator-clusterinstance-viewer-role
rules:
- apiGroups:
  - guestcluster.opdev.io
  resources:
  - clusterinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - guestcluster.opdev.io
  resources:
  - clusterinstances/status
  verbs:
  - get
