resources:
- monitor.yaml

# Template patch for a trusted metrics certificate configuration. It requires
# a metrics-server-cert Secret and matching manager certificate configuration.
#patches:
#  - path: monitor_tls_patch.yaml
#    target:
#      kind: ServiceMonitor
