apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: guestcluster-operator
    app.kubernetes.io/managed-by: kustomize
  name: manager-cdi-clone-source
  namespace: system
rules:
- apiGroups:
  - cdi.kubevirt.io
  resources:
  - datavolumes/source
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: guestcluster-operator
    app.kubernetes.io/managed-by: kustomize
  name: manager-cdi-clone-source
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manager-cdi-clone-source
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
