resources:
- guestcluster_v1alpha1_crcbundle.yaml
- guestcluster_v1alpha1_clusterpool.yaml
- guestcluster_v1alpha1_clusterpool_hcp.yaml
- guestcluster_v1alpha1_clusterinstance.yaml
- guestcluster_v1alpha1_clusterlease.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
